### ISSUE TITLE
PersistentVolume in Kubernetes

### ISSUE THREAD

**Issue by Adriien-M** [UKHomeOffice/docker-clamav#43]
When I try to use a persistent volume for clamav database in Kubernetes I have this error from logs
![image](https://user-images.githubusercontent.com/927834/61114859-8465fb80-a491-11e9-9318-fdfd45211e3e.png)

I tried to change [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) in the Pod to use the right user and group :
```
securityContext:
        fsGroup: 998
        runAsGroup: 998
        runAsUser: 1000
```
Sadly it does not work either...
It is clearly a permission issue but I don't know how to solve it....
