### ISSUE TITLE
Added support of PUID and PGID

### ISSUE THREAD

**Issue by GAS85** [UKHomeOffice/docker-clamav#57]
Hello, currently when I try to expose sock to the local host and always get a permission error, that is because docker will create folder as root and provided user in container is bounded to the uid 1000. I have to set 777 or 767 permissions to the folder to avoid this.

Expectation is that created folder is accessible for a container as per defined user.

My compose file:
```
version: "3.6"
services:
  clamav:
    image: "quay.io/ukhomeofficedigital/clamav:latest"
    container_name: "clamav"
    volumes:
      - ${WORKINGDIR}/clamav/:/var/run/clamav/
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - CLAMD_SETTINGS_CSV=MaxFileSize=300M,LogVerbose=yes,PCREMaxFileSize=50M,StreamMaxLength=50M,LocalSocket=/var/run/clamav/clamd.ctl
```
